const movies = [
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/6EdKBYkB1ssgGjc249ud1L55o8d.jpg',
    genre_ids: [
      28,
      878,
      53],
    id: 848278,
    original_language: 'en',
    original_title: 'Jurassic Hunt',
    overview: 'Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!',
    popularity: 4475.053,
    poster_path: '/Czhr00kB8awffakEcQS5ON1ELm.jpg',
    release_date: '2021-08-23',
    title: 'Jurassic Hunt',
    video: false,
    vote_average: 4.7,
    vote_count: 50,
  },
];

export default movies;
